* DiY OpenPGP card
** What a OpenPGP card is?
   From Wikipedia:
   #+begin_quote
   In cryptography, the OpenPGP card is an ISO/IEC 7816-4, -8
   compatible smart card that is integrated with many OpenPGP
   functions. Using this smart card, various cryptographic tasks
   (encryption, decryption, digital signing/verification,
   authentication etc.) can be performed. It allows secure storage of
   secret key material; all versions of the protocol state, "Private
   keys and passwords cannot be read from the card with any command or
   function." However, new key pairs may be loaded onto the card
   at any time, overwriting the existing ones.
   #+end_quote

** Purpose of this repository
   This repository lists the steps and materials required to build
   your own OpenPGP card out of opensource hardware and software.

   It cost me around 25 euros but you'll probably be able to build
   your own for cheaper buying on Aliexpress or Ebay. If you're
   willing to wait 2-3 weeks you can buy everything for under 9 euros.


** Material list

   - STM32 Blue Pill [[https://www.amazon.fr/ARCELI-STM32F103C8T6-d%C3%A9veloppement-syst%C3%A8me-minimum/dp/B077MJKCVT/][Amazon]] [[https://fr.aliexpress.com/item/1005002317649315.html][Aliexpress]]
   - St-Link V2 [[https://www.amazon.fr/gp/product/B09HJQQ1C6/][Amazon]] [[https://fr.aliexpress.com/item/1766455290.html][Aliexpress]]

   (you can find both [[https://fr.aliexpress.com/item/32792513237.html][here]])


 
   
